/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISeed, ISeedInterface } from "../../../interfaces/treasury/ISeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISeed__factory {
  static readonly abi = _abi;
  static createInterface(): ISeedInterface {
    return new utils.Interface(_abi) as ISeedInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISeed {
    return new Contract(address, _abi, signerOrProvider) as ISeed;
  }
}
