/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrivateVaultPermission__factory } from "./PrivateVaultPermission__factory";
export { VaultHubPermission__factory } from "./VaultHubPermission__factory";
