/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iPrivateVaultSol from "./IPrivateVault.sol";
export { IVaultHub__factory } from "./IVaultHub__factory";
