/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateVaultCallee } from "./PrivateVaultCallee";
export type { PrivateVaultTypeHashs } from "./PrivateVaultTypeHashs";
export type { VaultHubCallee } from "./VaultHubCallee";
export type { VaultHubTypeHashs } from "./VaultHubTypeHashs";
