/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface PrivateVaultCalleeInterface extends utils.Interface {
  functions: {
    "GET_PRIVATE_DATA_BY_INDEX_PERMIT()": FunctionFragment;
    "GET_PRIVATE_DATA_BY_NAME_PERMIT()": FunctionFragment;
    "LABEL_IS_EXIST_PERMIT()": FunctionFragment;
    "LABEL_NAME_PERMIT()": FunctionFragment;
    "SAVE_WITHOUT_MINTING_PERMIT()": FunctionFragment;
    "UPDATE_VALIDATOR_PERMIT()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GET_PRIVATE_DATA_BY_INDEX_PERMIT"
      | "GET_PRIVATE_DATA_BY_NAME_PERMIT"
      | "LABEL_IS_EXIST_PERMIT"
      | "LABEL_NAME_PERMIT"
      | "SAVE_WITHOUT_MINTING_PERMIT"
      | "UPDATE_VALIDATOR_PERMIT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GET_PRIVATE_DATA_BY_INDEX_PERMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GET_PRIVATE_DATA_BY_NAME_PERMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LABEL_IS_EXIST_PERMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LABEL_NAME_PERMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAVE_WITHOUT_MINTING_PERMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPDATE_VALIDATOR_PERMIT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GET_PRIVATE_DATA_BY_INDEX_PERMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GET_PRIVATE_DATA_BY_NAME_PERMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LABEL_IS_EXIST_PERMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LABEL_NAME_PERMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAVE_WITHOUT_MINTING_PERMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPDATE_VALIDATOR_PERMIT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PrivateVaultCallee extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PrivateVaultCalleeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GET_PRIVATE_DATA_BY_INDEX_PERMIT(
      overrides?: CallOverrides
    ): Promise<[string]>;

    GET_PRIVATE_DATA_BY_NAME_PERMIT(
      overrides?: CallOverrides
    ): Promise<[string]>;

    LABEL_IS_EXIST_PERMIT(overrides?: CallOverrides): Promise<[string]>;

    LABEL_NAME_PERMIT(overrides?: CallOverrides): Promise<[string]>;

    SAVE_WITHOUT_MINTING_PERMIT(overrides?: CallOverrides): Promise<[string]>;

    UPDATE_VALIDATOR_PERMIT(overrides?: CallOverrides): Promise<[string]>;
  };

  GET_PRIVATE_DATA_BY_INDEX_PERMIT(overrides?: CallOverrides): Promise<string>;

  GET_PRIVATE_DATA_BY_NAME_PERMIT(overrides?: CallOverrides): Promise<string>;

  LABEL_IS_EXIST_PERMIT(overrides?: CallOverrides): Promise<string>;

  LABEL_NAME_PERMIT(overrides?: CallOverrides): Promise<string>;

  SAVE_WITHOUT_MINTING_PERMIT(overrides?: CallOverrides): Promise<string>;

  UPDATE_VALIDATOR_PERMIT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    GET_PRIVATE_DATA_BY_INDEX_PERMIT(
      overrides?: CallOverrides
    ): Promise<string>;

    GET_PRIVATE_DATA_BY_NAME_PERMIT(overrides?: CallOverrides): Promise<string>;

    LABEL_IS_EXIST_PERMIT(overrides?: CallOverrides): Promise<string>;

    LABEL_NAME_PERMIT(overrides?: CallOverrides): Promise<string>;

    SAVE_WITHOUT_MINTING_PERMIT(overrides?: CallOverrides): Promise<string>;

    UPDATE_VALIDATOR_PERMIT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    GET_PRIVATE_DATA_BY_INDEX_PERMIT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GET_PRIVATE_DATA_BY_NAME_PERMIT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    LABEL_IS_EXIST_PERMIT(overrides?: CallOverrides): Promise<BigNumber>;

    LABEL_NAME_PERMIT(overrides?: CallOverrides): Promise<BigNumber>;

    SAVE_WITHOUT_MINTING_PERMIT(overrides?: CallOverrides): Promise<BigNumber>;

    UPDATE_VALIDATOR_PERMIT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    GET_PRIVATE_DATA_BY_INDEX_PERMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GET_PRIVATE_DATA_BY_NAME_PERMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    LABEL_IS_EXIST_PERMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    LABEL_NAME_PERMIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SAVE_WITHOUT_MINTING_PERMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UPDATE_VALIDATOR_PERMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
