/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface PrivateVaultTypeHashsInterface extends utils.Interface {
  functions: {
    "PRIVATE_DOMAIN_NAME()": FunctionFragment;
    "PRIVATE_DOMAIN_TYPE_HASH()": FunctionFragment;
    "PRIVATE_DOMAIN_VERSION()": FunctionFragment;
    "PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH()": FunctionFragment;
    "PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH()": FunctionFragment;
    "PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH()": FunctionFragment;
    "PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH()": FunctionFragment;
    "PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH()": FunctionFragment;
    "PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PRIVATE_DOMAIN_NAME"
      | "PRIVATE_DOMAIN_TYPE_HASH"
      | "PRIVATE_DOMAIN_VERSION"
      | "PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH"
      | "PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH"
      | "PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH"
      | "PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH"
      | "PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH"
      | "PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PRIVATE_DOMAIN_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_DOMAIN_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_DOMAIN_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PRIVATE_DOMAIN_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_DOMAIN_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_DOMAIN_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PrivateVaultTypeHashs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PrivateVaultTypeHashsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PRIVATE_DOMAIN_NAME(overrides?: CallOverrides): Promise<[string]>;

    PRIVATE_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<[string]>;

    PRIVATE_DOMAIN_VERSION(overrides?: CallOverrides): Promise<[string]>;

    PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  PRIVATE_DOMAIN_NAME(overrides?: CallOverrides): Promise<string>;

  PRIVATE_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  PRIVATE_DOMAIN_VERSION(overrides?: CallOverrides): Promise<string>;

  PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    PRIVATE_DOMAIN_NAME(overrides?: CallOverrides): Promise<string>;

    PRIVATE_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    PRIVATE_DOMAIN_VERSION(overrides?: CallOverrides): Promise<string>;

    PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    PRIVATE_DOMAIN_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    PRIVATE_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    PRIVATE_DOMAIN_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PRIVATE_DOMAIN_NAME(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_DOMAIN_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_DOMAIN_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_GET_PRIVATE_DATA_BY_INDEX_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_GET_PRIVATE_DATA_BY_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_LABEL_EXIST_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_LABEL_NAME_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_SAVE_WITHOUT_MINTING_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRIVATE_UPDATE_VALIDATOR_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
