/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface VaultHubTypeHashsInterface extends utils.Interface {
  functions: {
    "VAULTHUB_DOMAIN_NAME()": FunctionFragment;
    "VAULTHUB_DOMAIN_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_DOMAIN_VERSION()": FunctionFragment;
    "VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_LABEL_EXIST_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_SAVE_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH()": FunctionFragment;
    "VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "VAULTHUB_DOMAIN_NAME"
      | "VAULTHUB_DOMAIN_TYPE_HASH"
      | "VAULTHUB_DOMAIN_VERSION"
      | "VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH"
      | "VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH"
      | "VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH"
      | "VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH"
      | "VAULTHUB_LABEL_EXIST_TYPE_HASH"
      | "VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH"
      | "VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH"
      | "VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH"
      | "VAULTHUB_SAVE_PERMIT_TYPE_HASH"
      | "VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH"
      | "VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "VAULTHUB_DOMAIN_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_DOMAIN_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_DOMAIN_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_LABEL_EXIST_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_SAVE_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "VAULTHUB_DOMAIN_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_DOMAIN_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_DOMAIN_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_LABEL_EXIST_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_SAVE_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH",
    data: BytesLike
  ): Result;

  events: {};
}

export interface VaultHubTypeHashs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultHubTypeHashsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VAULTHUB_DOMAIN_NAME(overrides?: CallOverrides): Promise<[string]>;

    VAULTHUB_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<[string]>;

    VAULTHUB_DOMAIN_VERSION(overrides?: CallOverrides): Promise<[string]>;

    VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_LABEL_EXIST_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;

    VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  VAULTHUB_DOMAIN_NAME(overrides?: CallOverrides): Promise<string>;

  VAULTHUB_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  VAULTHUB_DOMAIN_VERSION(overrides?: CallOverrides): Promise<string>;

  VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_LABEL_EXIST_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_SAVE_PERMIT_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    VAULTHUB_DOMAIN_NAME(overrides?: CallOverrides): Promise<string>;

    VAULTHUB_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    VAULTHUB_DOMAIN_VERSION(overrides?: CallOverrides): Promise<string>;

    VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_LABEL_EXIST_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_SAVE_PERMIT_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;

    VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    VAULTHUB_DOMAIN_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    VAULTHUB_DOMAIN_TYPE_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    VAULTHUB_DOMAIN_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_LABEL_EXIST_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VAULTHUB_DOMAIN_NAME(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_DOMAIN_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_DOMAIN_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_GET_LABEL_NAME_BY_INDEX_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_HAS_MINTED_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_INDEX_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_INIT_VAULT_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_LABEL_EXIST_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_MINT_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_NAME_QUERY_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_QUERY_PRIVATE_VAULT_ADDRESS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_SAVE_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_TOTAL_SAVED_ITEMS_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VAULTHUB_VAULT_HAS_REGISTER_PERMIT_TYPE_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
