/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateVaultPermission } from "./PrivateVaultPermission";
export type { VaultHubPermission } from "./VaultHubPermission";
