/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as seedSol from "./Seed.sol";
export type { seedSol };
export type { Treasury } from "./Treasury";
