/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface TreasuryInterface extends utils.Interface {
  functions: {
    "addRule(string)": FunctionFragment;
    "callable()": FunctionFragment;
    "caller()": FunctionFragment;
    "cycle()": FunctionFragment;
    "enableHalf()": FunctionFragment;
    "lastWithdrawAmount()": FunctionFragment;
    "mint(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "ruleSize()": FunctionFragment;
    "rules(uint16)": FunctionFragment;
    "seedToken()": FunctionFragment;
    "setCaller(address)": FunctionFragment;
    "setHalf(bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw(address,address,uint256)": FunctionFragment;
    "withdrawCnt()": FunctionFragment;
    "withdrawETH(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addRule"
      | "callable"
      | "caller"
      | "cycle"
      | "enableHalf"
      | "lastWithdrawAmount"
      | "mint"
      | "owner"
      | "ruleSize"
      | "rules"
      | "seedToken"
      | "setCaller"
      | "setHalf"
      | "transferOwnership"
      | "withdraw"
      | "withdrawCnt"
      | "withdrawETH"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addRule", values: [string]): string;
  encodeFunctionData(functionFragment: "callable", values?: undefined): string;
  encodeFunctionData(functionFragment: "caller", values?: undefined): string;
  encodeFunctionData(functionFragment: "cycle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "enableHalf",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastWithdrawAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mint", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ruleSize", values?: undefined): string;
  encodeFunctionData(functionFragment: "rules", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "seedToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "setCaller", values: [string]): string;
  encodeFunctionData(functionFragment: "setHalf", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCnt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addRule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "caller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cycle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enableHalf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastWithdrawAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ruleSize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seedToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCaller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHalf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCnt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Treasury extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TreasuryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addRule(
      rule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callable(overrides?: CallOverrides): Promise<[boolean]>;

    caller(overrides?: CallOverrides): Promise<[string]>;

    cycle(overrides?: CallOverrides): Promise<[number]>;

    enableHalf(overrides?: CallOverrides): Promise<[boolean]>;

    lastWithdrawAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    ruleSize(overrides?: CallOverrides): Promise<[number]>;

    rules(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    seedToken(overrides?: CallOverrides): Promise<[string]>;

    setCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setHalf(
      enable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      receiver: string,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawCnt(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawETH(
      receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addRule(
    rule: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callable(overrides?: CallOverrides): Promise<boolean>;

  caller(overrides?: CallOverrides): Promise<string>;

  cycle(overrides?: CallOverrides): Promise<number>;

  enableHalf(overrides?: CallOverrides): Promise<boolean>;

  lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  ruleSize(overrides?: CallOverrides): Promise<number>;

  rules(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  seedToken(overrides?: CallOverrides): Promise<string>;

  setCaller(
    _caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setHalf(
    enable: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    receiver: string,
    tokenAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawCnt(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawETH(
    receiver: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addRule(rule: string, overrides?: CallOverrides): Promise<void>;

    callable(overrides?: CallOverrides): Promise<boolean>;

    caller(overrides?: CallOverrides): Promise<string>;

    cycle(overrides?: CallOverrides): Promise<number>;

    enableHalf(overrides?: CallOverrides): Promise<boolean>;

    lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mint(receiver: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    ruleSize(overrides?: CallOverrides): Promise<number>;

    rules(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    seedToken(overrides?: CallOverrides): Promise<string>;

    setCaller(_caller: string, overrides?: CallOverrides): Promise<void>;

    setHalf(enable: boolean, overrides?: CallOverrides): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      receiver: string,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdrawCnt(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawETH(
      receiver: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addRule(
      rule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callable(overrides?: CallOverrides): Promise<BigNumber>;

    caller(overrides?: CallOverrides): Promise<BigNumber>;

    cycle(overrides?: CallOverrides): Promise<BigNumber>;

    enableHalf(overrides?: CallOverrides): Promise<BigNumber>;

    lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    ruleSize(overrides?: CallOverrides): Promise<BigNumber>;

    rules(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    seedToken(overrides?: CallOverrides): Promise<BigNumber>;

    setCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setHalf(
      enable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      receiver: string,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawCnt(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawETH(
      receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addRule(
      rule: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    caller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cycle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enableHalf(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastWithdrawAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ruleSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rules(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seedToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setCaller(
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setHalf(
      enable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      receiver: string,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCnt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawETH(
      receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
