/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as treasury from "./treasury";
export type { treasury };
import type * as validator from "./validator";
export type { validator };
import type * as vaults from "./vaults";
export type { vaults };
