/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ISeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISeed__factory>;
    getContractFactory(
      name: "ITreasury",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITreasury__factory>;
    getContractFactory(
      name: "IValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IValidator__factory>;
    getContractFactory(
      name: "IWorker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWorker__factory>;
    getContractFactory(
      name: "IPrivateVaultHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrivateVaultHub__factory>;
    getContractFactory(
      name: "IVaultHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultHub__factory>;
    getContractFactory(
      name: "CalleeName",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CalleeName__factory>;
    getContractFactory(
      name: "Constant",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constant__factory>;
    getContractFactory(
      name: "PrivateVaultCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateVaultCallee__factory>;
    getContractFactory(
      name: "PrivateVaultTypeHashs",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateVaultTypeHashs__factory>;
    getContractFactory(
      name: "VaultHubCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultHubCallee__factory>;
    getContractFactory(
      name: "VaultHubTypeHashs",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultHubTypeHashs__factory>;
    getContractFactory(
      name: "PrivateVaultPermission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateVaultPermission__factory>;
    getContractFactory(
      name: "VaultHubPermission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultHubPermission__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "SeedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SeedToken__factory>;
    getContractFactory(
      name: "Treasury",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Treasury__factory>;
    getContractFactory(
      name: "PrivateValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateValidator__factory>;
    getContractFactory(
      name: "Validator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Validator__factory>;
    getContractFactory(
      name: "Worker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Worker__factory>;
    getContractFactory(
      name: "PrivateVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateVault__factory>;
    getContractFactory(
      name: "VaultHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultHub__factory>;

    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ISeed",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISeed>;
    getContractAt(
      name: "ITreasury",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITreasury>;
    getContractAt(
      name: "IValidator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IValidator>;
    getContractAt(
      name: "IWorker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWorker>;
    getContractAt(
      name: "IPrivateVaultHub",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrivateVaultHub>;
    getContractAt(
      name: "IVaultHub",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultHub>;
    getContractAt(
      name: "CalleeName",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CalleeName>;
    getContractAt(
      name: "Constant",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constant>;
    getContractAt(
      name: "PrivateVaultCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateVaultCallee>;
    getContractAt(
      name: "PrivateVaultTypeHashs",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateVaultTypeHashs>;
    getContractAt(
      name: "VaultHubCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultHubCallee>;
    getContractAt(
      name: "VaultHubTypeHashs",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultHubTypeHashs>;
    getContractAt(
      name: "PrivateVaultPermission",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateVaultPermission>;
    getContractAt(
      name: "VaultHubPermission",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultHubPermission>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "SeedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SeedToken>;
    getContractAt(
      name: "Treasury",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Treasury>;
    getContractAt(
      name: "PrivateValidator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateValidator>;
    getContractAt(
      name: "Validator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Validator>;
    getContractAt(
      name: "Worker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Worker>;
    getContractAt(
      name: "PrivateVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateVault>;
    getContractAt(
      name: "VaultHub",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultHub>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
