/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWorker,
  IWorkerInterface,
} from "../../../interfaces/validator/IWorker";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "run",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWorker__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkerInterface {
    return new utils.Interface(_abi) as IWorkerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWorker {
    return new Contract(address, _abi, signerOrProvider) as IWorker;
  }
}
